### ISSUE TITLE
Linux cRIO Support

### ISSUE THREAD

**Issue by ssummers-lime** [rfporter/LV-muParser#1]
Has this been tested on Linux cRIO systems? If not, can you compile the muParser for the Linux cRIO?

**Comment by rfporter** [comment]
I imagine that you can compile muParser for a Linux cRIO. You would need to make sure that labview can find the libmuParser shared object on the target by name (so probably copy it to /usr/lib on the target). As of V2.1.0, 32-bit targets assume that the shared object file is named libmuparser-x32-lv.so and 64-bit targets assume that it is named libmuparser-x64-lv.so.
